before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - pip install -r requirements.txt --upgrade
    - python setup.py develop

stages:
  - test
  - build

test:
    script:
        - pytest

docs:
    stage: build
    only:
    - master
    script:
        - pip install sphinx sphinx_rtd_theme recommonmark
        - cd doc
        - make clean html upload

release:
    stage: build
    script:
    - python setup.py sdist bdist_wheel
    - make release
    only:
    - release

